name: My First Workflow
on:
  workflow_dispatch:  
  #schedule:
  #  - cron: "*/1 * * * *"

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List and Readfile
        run: |
            echo "My first Github Actions Job"
            ls -ltra
            cat README.md
      
      - name: GENERATE ASCII Artwork 
        run: cosway -f dragon "Run for cover, i am a Dragon....RAWR" >> dragon.txt

      # - name: List files
      #  run: ls
      # - name:
      #  run: cat README.md